"""Fixed: autoincrement

Revision ID: 39f1c1cebd6b
Revises: fc8ebd8b019d
Create Date: 2025-02-13 13:57:42.306251

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "39f1c1cebd6b"
down_revision: Union[str, None] = "fc8ebd8b019d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "test_model",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_test_model_id"), "test_model", ["id"], unique=False)
    op.create_index(op.f("ix_test_model_name"), "test_model", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_test_model_name"), table_name="test_model")
    op.drop_index(op.f("ix_test_model_id"), table_name="test_model")
    op.drop_table("test_model")
    # ### end Alembic commands ###
