"""

Revision ID: 77e752dc5fca
Revises: 39f1c1cebd6b
Create Date: 2025-02-13 14:33:06.540169

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "77e752dc5fca"
down_revision: Union[str, None] = "39f1c1cebd6b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
