"""create test_model

Revision ID: 86441e8dfa0b
Revises: 
Create Date: 2025-02-05 12:23:28.935470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86441e8dfa0b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_model_id'), 'test_model', ['id'], unique=False)
    op.create_index(op.f('ix_test_model_name'), 'test_model', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_model_name'), table_name='test_model')
    op.drop_index(op.f('ix_test_model_id'), table_name='test_model')
    op.drop_table('test_model')
    # ### end Alembic commands ###
