"""Create initial tables

Revision ID: 9aca449a376b
Revises: 86441e8dfa0b
Create Date: 2025-02-06 10:36:20.230158

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "9aca449a376b"
down_revision: Union[str, None] = "86441e8dfa0b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
