"""Fixed: datetime

Revision ID: fc8ebd8b019d
Revises: 2087b951e000
Create Date: 2025-02-13 13:49:23.108548

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fc8ebd8b019d"
down_revision: Union[str, None] = "2087b951e000"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("accounts", sa.Column("is_active", sa.Boolean(), nullable=True))
    op.add_column("accounts", sa.Column("is_deleted", sa.Boolean(), nullable=True))
    op.alter_column(
        "accounts",
        "bank_code",
        existing_type=postgresql.ENUM(
            "알수없음", "한국은행", "산업은행", "기업은행", "국민은행", name="bankcode"
        ),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "accounts",
        "account_type",
        existing_type=postgresql.ENUM(
            "CHECKING",
            "SAVING",
            "LOAN",
            "PENSION",
            "TRUST",
            "FOREIGN_CURRENCY",
            "IRP",
            "STOCK",
            name="accounttype",
        ),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "analysis",
        "analysis_type",
        existing_type=postgresql.ENUM(
            "DAILY", "WEEKLY", "MONTHLY", "YEARLY", name="analysistype"
        ),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "analysis",
        "analysis_about",
        existing_type=postgresql.ENUM(
            "TOTAL_SPENDING", "TOTAL_INCOME", name="analysisabout"
        ),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "transactions",
        "transaction_type",
        existing_type=postgresql.ENUM("DEPOSIT", "WITHDRAW", name="transactiontype"),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "transactions",
        "transaction_method",
        existing_type=postgresql.ENUM(
            "ATM",
            "TRANSFER",
            "AUTOMATIC_TRANSFER",
            "CARD",
            "INTEREST",
            name="transactionmethod",
        ),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.add_column("users", sa.Column("is_active", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_active")
    op.alter_column(
        "transactions",
        "transaction_method",
        existing_type=sa.String(),
        type_=postgresql.ENUM(
            "ATM",
            "TRANSFER",
            "AUTOMATIC_TRANSFER",
            "CARD",
            "INTEREST",
            name="transactionmethod",
        ),
        existing_nullable=False,
    )
    op.alter_column(
        "transactions",
        "transaction_type",
        existing_type=sa.String(),
        type_=postgresql.ENUM("DEPOSIT", "WITHDRAW", name="transactiontype"),
        existing_nullable=False,
    )
    op.alter_column(
        "analysis",
        "analysis_about",
        existing_type=sa.String(),
        type_=postgresql.ENUM("TOTAL_SPENDING", "TOTAL_INCOME", name="analysisabout"),
        existing_nullable=False,
    )
    op.alter_column(
        "analysis",
        "analysis_type",
        existing_type=sa.String(),
        type_=postgresql.ENUM(
            "DAILY", "WEEKLY", "MONTHLY", "YEARLY", name="analysistype"
        ),
        existing_nullable=False,
    )
    op.alter_column(
        "accounts",
        "account_type",
        existing_type=sa.String(),
        type_=postgresql.ENUM(
            "CHECKING",
            "SAVING",
            "LOAN",
            "PENSION",
            "TRUST",
            "FOREIGN_CURRENCY",
            "IRP",
            "STOCK",
            name="accounttype",
        ),
        existing_nullable=False,
    )
    op.alter_column(
        "accounts",
        "bank_code",
        existing_type=sa.String(),
        type_=postgresql.ENUM("알수없음", "한국은행", "산업은행", "기업은행", "국민은행", name="bankcode"),
        existing_nullable=False,
    )
    op.drop_column("accounts", "is_deleted")
    op.drop_column("accounts", "is_active")
    # ### end Alembic commands ###
